# Generated by Django 5.0.3 on 2024-04-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imagem', models.FileField(default='fotos/sem-foto.png', null=True, upload_to='fotos/clientes')),
                ('assinatura', models.FileField(db_index=True, null=True, upload_to='assinaturas/clientes')),
                ('is_email_confirmado', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': '"public"."cliente"',
            },
        ),
    ]
