# Generated by Django 5.0.3 on 2024-04-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_assinatura_cliente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='username',
        ),
    ]
