# Generated by Django 5.0.3 on 2024-04-05 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_user_cliente_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nm_descritivo', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': '"public"."perfis"',
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.perfis')),
            ],
            options={
                'db_table': '"public"."perfil_cliente"',
            },
        ),
    ]
