# Generated by Django 5.0.3 on 2024-04-16 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_perfis_perfilcliente'),
        ('esporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.perfis'),
        ),
        migrations.CreateModel(
            name='ClientePreferencias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('esporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.esporte')),
            ],
            options={
                'db_table': '"public"."cliente_preferencias"',
            },
        ),
        migrations.DeleteModel(
            name='PerfilCliente',
        ),
    ]
