# Generated by Django 5.0.3 on 2024-04-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_status_clientepreferencias_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepreferencias',
            name='campeonato',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientepreferencias',
            name='esporte',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
