# Generated by Django 5.0.3 on 2024-04-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_cliente_codigo_recuperacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepreferencias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
