# Generated by Django 5.0.3 on 2024-04-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_clientepreferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
