# Generated by Django 5.0.3 on 2024-04-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_cliente_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='altura',
        ),
    ]
