# Generated by Django 5.0.3 on 2024-04-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_remove_cliente_altura'),
        ('cliente', '0013_remove_cliente_apelido'),
    ]

    operations = [
    ]
