# Generated by Django 5.0.3 on 2024-04-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_merge_20240425_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
