# Generated by Django 5.0.3 on 2024-05-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_remove_cliente_cor'),
        ('esporte', '0018_evento_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('palpite', models.CharField(max_length=500, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.evento')),
            ],
            options={
                'db_table': '"public"."aposta"',
            },
        ),
    ]
