# Generated by Django 5.0.3 on 2024-06-05 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_aposta'),
        ('esporte', '0018_evento_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='palpite',
            new_name='odd',
        ),
        migrations.AddField(
            model_name='aposta',
            name='campeonato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.campeonato'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='time_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_1', to='esporte.time'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='time_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_2', to='esporte.time'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='tipo_aposta',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
