# Generated by Django 5.0.3 on 2024-06-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_rename_palpite_aposta_odd_aposta_campeonato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
