# Generated by Django 5.0.3 on 2024-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0019_aposta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='is_aposta',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
