# Generated by Django 5.0.3 on 2024-06-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_aposta_is_aposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='casa_aposta',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientepreferencias',
            name='stack_aposta',
            field=models.FloatField(null=True),
        ),
    ]
