# Generated by Django 5.0.3 on 2024-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0022_perfis_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
