# Generated by Django 5.0.3 on 2024-08-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_alter_cliente_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientepreferencias',
            name='campeonato',
        ),
        migrations.RemoveField(
            model_name='clientepreferencias',
            name='esporte',
        ),
        migrations.RemoveField(
            model_name='clientepreferencias',
            name='opcoes_apostas',
        ),
        migrations.AddField(
            model_name='clientepreferencias',
            name='id_preferencia',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientepreferencias',
            name='tipo_preferencia',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
