# Generated by Django 5.0.3 on 2024-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0024_remove_clientepreferencias_campeonato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientepreferencias',
            name='stack_aposta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='stack_aposta',
            field=models.FloatField(null=True),
        ),
    ]
