# Generated by Django 5.0.3 on 2024-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_remove_clientepreferencias_stack_aposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='stack_aposta',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
