# Generated by Django 5.0.3 on 2024-10-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0028_clienteassinatura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteCarteira',
        ),
    ]
