# Generated by Django 5.0.3 on 2024-04-16 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '"public"."esporte"',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '"public"."time"',
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('esporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.esporte')),
            ],
            options={
                'db_table': '"public"."campeonato"',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('data', models.IntegerField(null=True)),
                ('campeonato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.campeonato')),
                ('resultado_time_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultado_time_a', to='esporte.time')),
                ('resultado_time_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultado_time_b', to='esporte.time')),
                ('time_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_a', to='esporte.time')),
                ('time_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_b', to='esporte.time')),
            ],
            options={
                'db_table': '"public"."evento"',
            },
        ),
    ]
