# Generated by Django 5.0.3 on 2024-04-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0004_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
