# Generated by Django 5.0.3 on 2024-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0005_delete_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('informacao', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': '"public"."tipo"',
            },
        ),
    ]
