# Generated by Django 5.0.3 on 2024-04-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0006_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
