# Generated by Django 5.0.3 on 2024-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0007_alter_tipo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.CharField(null=True),
        ),
    ]
