# Generated by Django 5.0.3 on 2024-05-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0008_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='resultado_time_a',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='resultado_time_b',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
