# Generated by Django 5.0.3 on 2024-05-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0010_remove_evento_resultado_time_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='resultado_time_a',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='resultado_time_b',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
