# Generated by Django 5.0.3 on 2024-05-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0011_evento_resultado_time_a_evento_resultado_time_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': '"public"."season"',
            },
        ),
        migrations.CreateModel(
            name='PerformaceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('campeonato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.campeonato')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.time')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.season')),
            ],
            options={
                'db_table': '"public"."performaceTime"',
            },
        ),
    ]
