# Generated by Django 5.0.3 on 2024-05-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0012_season_performacetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performacetime',
            name='campeonato',
        ),
        migrations.AddField(
            model_name='season',
            name='dat_fim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='dat_inicio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
