# Generated by Django 5.0.3 on 2024-05-22 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0014_remove_performacetime_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('dat_inicio', models.CharField(max_length=100, null=True)),
                ('dat_fim', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': '"public"."season"',
            },
        ),
        migrations.CreateModel(
            name='PerformaceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.time')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.season')),
            ],
            options={
                'db_table': '"public"."performaceTime"',
            },
        ),
    ]
