# Generated by Django 5.0.3 on 2024-05-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0015_season_performacetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformaceTime',
        ),
    ]
