# Generated by Django 5.0.3 on 2024-05-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0016_delete_performacetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformaceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.season')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.time')),
            ],
            options={
                'db_table': '"public"."performace_time"',
            },
        ),
    ]
