# Generated by Django 5.0.3 on 2024-05-23 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0017_performacetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.season'),
        ),
    ]
