# Generated by Django 5.0.3 on 2024-07-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0018_evento_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='season_atual',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
