# Generated by Django 5.0.3 on 2024-07-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0019_campeonato_season_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performacetime',
            name='season',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='season',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
