# Generated by Django 5.0.3 on 2024-07-31 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0020_alter_performacetime_season_alter_evento_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='nome',
        ),
    ]
