# Generated by Django 5.0.3 on 2024-07-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0021_remove_evento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performacetime',
            name='info',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
