# Generated by Django 5.0.3 on 2024-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0022_alter_performacetime_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('informacao', models.CharField(max_length=200, null=True)),
                ('tipo_operacao', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '"public"."log"',
            },
        ),
    ]
