# Generated by Django 5.0.3 on 2024-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0025_tipo_codigo_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='imagem',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
