# Generated by Django 5.0.3 on 2024-09-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0026_campeonato_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='classificacao',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
