# Generated by Django 5.0.3 on 2024-09-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0027_campeonato_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='classificacao',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
