# Generated by Django 5.0.3 on 2024-10-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporte', '0028_alter_campeonato_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('informacao', models.CharField(max_length=200, null=True)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.evento')),
                ('tipo_aposta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esporte.tipo')),
            ],
            options={
                'db_table': '"public"."evento_recomendacao"',
            },
        ),
    ]
